### ISSUE TITLE
CI構築

### ISSUE THREAD

**Issue by cotton-alta** [stlatica/stlatica#10]

**Comment by cotton-alta** [comment]
@Percy08-dev 

お待たせしました、以下がbackendで設定して欲しいCIの内容になります:bow:
（ビルド、デプロイについてはCD構築のissueで対応することになりそうなのでこちらには含めてません）

## golangci-lintの実行
actionが用意されているようなのでこれをそのまま使うと良さそうです（working_directoryの変更とかは必要そうだけど）
https://golangci-lint.run/usage/install/#github-actions

**Comment by Percy08-dev** [comment]
golangci-lintのバージョンは、常に最新版でいいですか？

**Comment by cotton-alta** [comment]
@Percy08-dev 
はい、最新版を使用する、で大丈夫です！🙆‍♂️（breaking changeでCI通らなくなるとかあったらその時にversion固定などの対応をとりましょう）

**Comment by cotton-alta** [comment]
https://github.com/stlatica/stlatica/pull/38 で対応していただいたのでcloseします
