### ISSUE TITLE
フォロー・フォロー解除ボタン

### ISSUE THREAD

**Issue by para7** [stlatica/stlatica#121]
# Overview

ボタンのデザインを作成する

# Completion Condition

ladleでデザインが確認できる

# Reviewer

# Sub Task

- [ ] Sub Task1
- [ ] Sub Task2

**Comment by nobuchi** [comment]
@para7 

pnpm plop で FollowButton を生成したのでこれをもとに作っていこうと思います。

以下２点質問させてください。

1. フォローボタンとフォロー解除ボタンは同一のコンポーネントとして作成しますか？別々に作りますか？
2. ユーザ情報、フォロー中かどうかの状態などを取得するためのAPIの情報はどこから確認すれば良いでしょうか？

**Comment by para7** [comment]
> フォローボタンとフォロー解除ボタンは同一のコンポーネントとして作成しますか？別々に作りますか？

実際に画面から置くときには1種類じゃないと配置するとき複雑になって困るので、1種が良さそうです。→A

一方で実際の実装としては色の変更などで2種で実装したほうがやりやすい可能性はあります。→B

---

A

コンポーネントのインターフェースとしては1種にまとめたいので

```
<FollowButton isFollow={true}/ >
```

のように、表示状態を引数で受け取るのがよさそうです。

---

B

FollowButton 内部では、今回の規模ですと愚直に書いても問題なさそうですが

```
if( isFollow ) {
  reutrn <UnFollowAPIButton>
}
return <FollowAPIButton>
```

のように2種に分けて実装することもできます（あんまり良い名称が浮かばなかった…

実際FollowButtonを作ってみて、別物として作った方がよさそうだと感じたらこのようにしてみてください.

----

----

---

> ユーザ情報、フォロー中かどうかの状態などを取得するためのAPIの情報はどこから確認すれば良いでしょうか？

フォロー中かどうかやユーザーIDは、ボタンとしてAPIが受け取るのではなく、一旦は直接bool値を受け取るような形式でお願いします。
そうでないとボタン単体での確認がすぐできないためです。

「[純粋関数](https://scrapbox.io/stlatica/%E7%B4%94%E7%B2%8B%E9%96%A2%E6%95%B0)」という概念があるのですが、末端ノードは基本的にこれに沿って設計しておけば間違いないのでこんな感じでお願いします。

この例でいうと、フォローしている・していないの情報や、対象ユーザーの情報などは外部からの引数に依存させておき、ボタン内部ではそれらの情報を持たないようにしておくイメージです。
今はできる限り外部に依存させるようにしておくと変更に強く、汎用性も高まるので後で楽になります。

言い方を変えると、面倒な作業（APIとのやり取り）はできるだけ末端で実施せず基本的に呼び出し元に押し付けていきます。その方が個々の持つ責任が軽くなり、バグも含みにくいので、設計として堅牢になります。

---

上記踏まえてとりあえずフォローボタンとしてはこんな感じで実装をお願いします

1. 必要そうな情報をボタンの prop として設定しておく
2. ボタンを押下するとその情報が console.log に表示される

---

**Comment by para7** [comment]
ついでにいうと、システム全体として使う汎用的なボタンも必要かもしれません.

SubmitButton
CancelButton

みたいな

FollowButton / UnFollow ボタンもそれを使って実装されている感じの。

**Comment by nobuchi** [comment]
> 上記踏まえてとりあえずフォローボタンとしてはこんな感じで実装をお願いします
> 
> 必要そうな情報をボタンの prop として設定しておく
> ボタンを押下するとその情報が console.log に表示される

フォローボタンをクリックしたときにサーバと通信してisFollowの真偽値をを反転させ、その結果を元に フォロー / フォロー中 の状態を切り替えると思いますが、これでは純粋関数になりません。今回は単にpropからのisFollowの値をローカルの状態としてコピーして、それをクリックするごとに状態が反転するという形の実装をするべきでしょうか？

もしくは現段階ではpropの取得とコンソール表示だけでクリックによる反転は行わないということでしょか？

**Comment by para7** [comment]
@nobuchi 

> フォローボタンをクリックしたときにサーバと通信してisFollowの真偽値をを反転させ、その結果を元に フォロー / フォロー中 の状態を切り替えると思いますが、これでは純粋関数になりません。今回は単にpropからのisFollowの値をローカルの状態としてコピーして、それをクリックするごとに状態が反転するという形の実装をするべきでしょうか？

コンポーネントとしては「isFollowの真偽値を受け取る」だけであれば、どこから受け取るかはボタンとして関与してないので純粋関数です。


渡す側がAPIの値を使っていたとしても、「フォローボタンとしては最終的にprop（引数）として渡された true / false の値だけを見て仕事に専念すればいい」、という状態になっていれば何も問題なく純粋関数です。

「ボタン単品で呼んだときに、引数が同じなら必ず同じ結果が出力されるか？」が純粋関数かどうかの判別手段になります。

とりあえずボタン内部でAPI呼んでなければOKです！

----

この辺のUIについては楽観更新という概念がありますので紹介しておきます。
**他色々なコンポーネントとの兼ね合いでエラーハンドリングの挙動を決めないといけないので、今は楽観更新まで実装しなくていいです！**

https://zenn.dev/syoo/articles/f034b983d4fd8e

**Comment by para7** [comment]
だいたい私が直しちゃいましたが、最初のコンポーネントですし例ということでこれで完了とします！
