### ISSUE TITLE
OpenAPI → HTML 生成

### ISSUE THREAD

**Issue by para7** [stlatica/stlatica#136]
# Overview

OpenAPIの定義生成

# Completion Condition

OpenAPIからHTMLの生成

# Reviewer

# Sub Task

**Comment by para7** [comment]
HTMLの生成ですが、昨日業務でやったばかりなので私に任せてもらって大丈夫です

**Comment by para7** [comment]
考えたらこれinternalとexternalどっちホスティングするんだ…？

**Comment by cotton-alta** [comment]
HTMLの吐き出し準備まではやってもらってもいいと思うのですが、そもそもpagesでホスティングするかそれともS3とかに載せるのか、そこから話した方が良さそうです

**Comment by para7** [comment]
> ホスティングのためにopenapiの定義書き換えは出来ればやりたくないです（元の記述と異なり利用者が混乱する原因にもなると思います）

もちろんこれはやるつもり無くて、無理やりバンドルして上手くできないかな？って思ったのですが…
よく考えたらinternalとexternalを同時に使うことはないので仕様書ごと分けたままでいいですね。

> HTMLの吐き出し準備まではやってもらってもいいと思うのですが、そもそもpagesでホスティングするかそれともS3とかに載せるのか、そこから話した方が良さそうです

すみません、早とちりしてた部分があるのでチケット修正しました
（S3いますぐ用意してすぐデプロイ出来るか微妙だと思っていたので、当分の進捗で大きな影響出るAPI仕様書部分をホスティング変えると思ってました）

ドキュメントが2つ生まれる以上、github pagesでのホスティングが1つしかできないならOpenAPIを置くのは微妙な感じもありますね
