### ISSUE TITLE
スナップショットテストでnanoidが毎回変わってエラーを起こす

### ISSUE THREAD

**Issue by nobuchi** [stlatica/stlatica#208]
# Overview

#188 にて、コンポーネントに固有のIDをnanoidで割り当てたのですが、スナップショットテストを行うたびにidが変更されてエラーを起こします。

b2cbab317a6f9ac6b27d759d57c3a5c2d3c72cdd
応急処置としてスナップショットをコメントアウトしています。

ご対応お願いします。

![image](https://github.com/stlatica/stlatica/assets/79183832/247283c1-f829-4dc0-80ea-a1676eb52a7b)

**Comment by para7** [comment]
VRT導入してコンポーネントに対するスナップショットは削除対応予定

#112

**Comment by para7** [comment]
クローズもれ

vrt導入で解消済
