### ISSUE TITLE
URL定義

### ISSUE THREAD

**Issue by para7** [stlatica/stlatica#230]
# Overview

フロント画面のURL定義を行う

layout.tsx による処理共通化※1や画面遷移時間と、ユーザー利用時のシンプルさなど加味して設計する必要あり

---
※1 layout.tsx について: https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts

画面の枠となる部分は使いまわせるので、階層構造をそれに沿わせるということ。
設定画面であれば、
- settting/-
- setting/user
- setting/privacy 

という感じでURLを用意し、src/app/setting/layout.tsx に処理を書くと layout が全てのページに適用できるので、このあたり画面構造を加味して作る

// 共通枠部分はそんなに多くないと想定しているが、実際どうかはやってみないと分からない

---

設定画面の中身などまだ決めようがない部分はあるが、ワイヤーフレームを見てとりあえず決定できそうな部分のみ仮決定のような形でも問題なし

# Completion Condition

scrapboxにまとめるか、 figma に書いてまとめるどちらかあたり？

上記にこだわる必要もないので、わかりやすい形でまとまっていればとりあえずOK（清書は別で書き起こすなりしてもよいので）

完成品をいきなり渡してもらうより、ある程度書いた段階で投げてもらってやりとりしながら仕上げる形がよいと思います

# Reviewer

@para7 

# Sub Task

- [ ] Sub Task1
- [ ] Sub Task2

**Comment by nobuchi** [comment]
URLってスネークケースで良かったでしょうか？

**Comment by para7** [comment]
@nobuchi 
だいたいこんな感じで良いと思います、ありがとうございます。特に

> deck

が亡きtweetdeckを想起させていいなと個人的に思いました.

----

1点だけコメントとしては、/setting/aboutStlatica の部分については /about のみの方がよさそうです

試しにいろんなwebサイト開いてみて /about を開くと開けると思います。そこに統一する意図です

**Comment by para7** [comment]
@nobuchi 
すみません、追加の修正内容です

- ユーザー系は users/[ユーザーID]/xxxx のようにusers で1個掘ったほうが実装上都合よさそうです
- 命名はスネークケース（アンダーバー）でお願いします

**Comment by nobuchi** [comment]
@para7 

> ユーザー系は users/[ユーザーID]/xxxx のようにusers で1個掘ったほうが実装上都合よさそうです
> 命名はスネークケース（アンダーバー）でお願いします

こちらの修正も含めてScrapboxにまとめましたので確認をお願いします
[URL定義](https://scrapbox.io/stlatica/URL%E5%AE%9A%E7%BE%A9)

**Comment by para7** [comment]
暫定版としてまとまったので一旦完了とします
