### ISSUE TITLE
OpenAPI定義重複でフロントのコード生成に問題が生じている

### ISSUE THREAD

**Issue by para7** [stlatica/stlatica#248]
# Overview

キャメルケースで一致する名称の定義が存在しているため、フロントのクライアント生成でエラーが出ている

# detail

現在InternalAPIのOpenAPI定義にはuser_id と UserID がそれぞれあります。

フロントエンドのコード生成時にキャメルケースで生成される挙動があり、これにより問題が発生しているようです。

----

恐らく、ファイルシステムの仕様的として大文字小文字のみが異なる同名のファイルは存在できないため、上書きされる等で片方のファイルが消滅し、結果ビルドがコケるという現象が発生しています。

![image](https://github.com/stlatica/stlatica/assets/18499975/8dc1f0e8-b1f6-4656-af4c-0ba79caf4688)

↑ のように存在しないファイルインポートが発生

# other

フロントのコード生成通したかったので一旦こちらで別名に変更してTODO発行しています

https://github.com/stlatica/stlatica/pull/249/files#diff-0c222e29c15d7428022c873074a4fccf83643a016094916cd315e8a5f821e85c

**Comment by cotton-alta** [comment]
@para7 

以下のPRを見ると、全てのcomponent（schema、parameterなど）がmodelディレクトリ直下に格納されるようになっているように見えるのですが、modelディレクトリ配下でparametersなどディレクトリを別途切り分ける、という方法で回避できたりしますか？
（コード生成用のライブラリなど見てない状態の質問です）

https://github.com/stlatica/stlatica/pull/249

**Comment by para7** [comment]
@cotton-alta 
schemas の設定を切ると1ファイル生成されるのでエラーは回避できるようになりました。

1ファイルだとgit上の差分や可視性が落ちますが、生成物を確認する機会は少ないこと、ツリーシェイキング的にも問題なさそうなので一旦これで大丈夫そうです。ヒントありがとうございます！
