### ISSUE TITLE
mockサーバ用の設定を追加

### ISSUE THREAD

**Issue by cotton-alta** [stlatica/stlatica#27]
# Overview

# Completion Condition

# Reviewer

# Sub Task

- [ ] Sub Task1
- [ ] Sub Task2

**Comment by cotton-alta** [comment]
mockを使用するのは主にfrontendなのでこちらのタスクはpara7さんにdelegateします

https://github.com/stlatica/stlatica/pull/45 で既に対応してくださっている模様

**Comment by para7** [comment]
もうちょっと調整していく必要はありますが、利用する環境としては整いましたのでissueはクローズとさせて頂きます
