### ISSUE TITLE
issue 追加時に自動でproject割り当てして欲しい

### ISSUE THREAD

**Issue by para7** [stlatica/stlatica#270]
# Overview

しょっちゅう忘れるし、忘れると空中に浮く可能性があるので自動化してほしい

https://github.com/marketplace/actions/add-to-github-projects

bugのラベルが付いてるか否かで Minimum Structure と Bug Reports で振り分けもしてくれるとよい

# Completion Condition

# Reviewer

# Sub Task

- [ ] Sub Task1
- [ ] Sub Task2

**Comment by para7** [comment]
関連　#247

**Comment by Percy08-dev** [comment]
[これ](https://qiita.com/n_komiya/items/5e4533e4f4fd90036ea9)ベースで作ってみようかなと思います。

**Comment by para7** [comment]
動いてるので完了
