### ISSUE TITLE
ActivityPubとして必要な最小構成の整理

### ISSUE THREAD

**Issue by cotton-alta** [stlatica/stlatica#29]
# Overview
- 最小構成でMastodonなどに認識されるサーバを構成する
- 投稿が他のサーバから閲覧できるようにする構成は別で考える
# Completion Condition

# Reviewer

# Sub Task

- [ ] Sub Task1
- [ ] Sub Task2

**Comment by polyester-CTRL** [comment]
https://scrapbox.io/stlatica/ActivityPub%E3%81%A8%E3%81%97%E3%81%A6%E5%BF%85%E8%A6%81%E3%81%AA%E6%9C%80%E5%B0%8F%E6%A7%8B%E6%88%90%E3%81%AE%E6%95%B4%E7%90%86

とりあえずまとまりました。

**Comment by cotton-alta** [comment]
@polyester-CTRL 

2点ほどコメントしました 🙋‍♂️ 

---

何をする機能なのか + 例としてのAPI interfaceをセットで統一しておいてもらえると見やすくなると思います！

e.g.)
- nodeinfoを取得するendpoint
  - API interface: `GET  /nodeinfo/2.1`
  - etc.

---

参考にしたサイトにはパーマリンクも必要とあるのですが、いかがでしょう？
followなどはいらないにしても以下のようなActivityが取得できるendpointは必要になりそうな気がします:thinking:
複数のendpointに分けるかどうかは後で議論すれば良さそう

e.g.)
- Activityを取得するendpoint
  - API interface: `GET /activities/:activity_id`

**Comment by polyester-CTRL** [comment]
@cotton-alta 
書き足しました。よろしくお願いします。

**Comment by cotton-alta** [comment]
ありがとうございます！LGTMです:tada:

パーマリンクのところはAPI interfaceに落とし込む前にもう少し深掘らないといけなさそうですね:thinking:
まあ、このissueで対応の必要はないので問題無しです:ok_man:

**Comment by cotton-alta** [comment]
こちらはcloseしちゃいます
