### ISSUE TITLE
要件定義

### ISSUE THREAD

**Issue by cotton-alta** [stlatica/stlatica#3]
# Overview

# Completion Condition

# Reviewer

# Sub Task

- [ ] Sub Task1
- [ ] Sub Task2

**Comment by nobuchi** [comment]
@cotton-alta @para7 

必要な機能を目的別・UI別にまとめたので確認していただけるとありがたいです。
https://scrapbox.io/stlatica/%E8%A6%81%E4%BB%B6%E5%AE%9A%E7%BE%A9

**Comment by cotton-alta** [comment]
@nobuchi 

ちょっと不足してそうな箇所について追記したので違和感ないか確認していただけますか:pray:（追記した行には自分のアイコン貼ってます）

**Comment by nobuchi** [comment]
違和感ないと思います！

管理者向けの機能の追加もありがとうございます。

**Comment by cotton-alta** [comment]
確認ありがとうございます！
不足分についても追加したので、一旦こちらのissueはcloseで大丈夫です:ok_man:

対応お疲れ様でした:tada:
