### ISSUE TITLE
他実装との兼ね合いを考慮した構成の整理

### ISSUE THREAD

**Issue by cotton-alta** [stlatica/stlatica#30]
# Overview

# Completion Condition

# Reviewer

# Sub Task

- [ ] Sub Task1
- [ ] Sub Task2

**Comment by polyester-CTRL** [comment]
[他実装との兼ね合いを考慮した構成の整理 ](https://scrapbox.io/stlatica/%E4%BB%96%E5%AE%9F%E8%A3%85%E3%81%A8%E3%81%AE%E5%85%BC%E3%81%AD%E5%90%88%E3%81%84%E3%82%92%E8%80%83%E6%85%AE%E3%81%97%E3%81%9F%E6%A7%8B%E6%88%90%E3%81%AE%E6%95%B4%E7%90%86)
書きました。

実装時点で対応が必要となる仕様をまとめると、次の3点になります。
- HTTPリクエストに認証を付ける
- IDの変更は認めない
- preferredUsernameとwebfingerのacctを同一にする

**Comment by cotton-alta** [comment]
明日確認しますね🙏

**Comment by cotton-alta** [comment]
@polyester-CTRL 

対応ありがとうございます！

既に記載されているものについては大丈夫そうでした:ok_man:
（goの署名用ライブラリの提案が含まれていましたが、こちらについては更新が途絶えてる雰囲気を感じたので自作した方がいいかもですね... :innocent:）

---

記載されていなかった点について1つだけコメントです
拡張スキーマについて言及されていなかったのでこちらについても追記しておいていただきたいです:pray:
[ActivityPub標準ではないwell-knownな拡張スキーマ](https://scrapbox.io/activitypub/ActivityPub%E6%A8%99%E6%BA%96%E3%81%A7%E3%81%AF%E3%81%AA%E3%81%84well-known%E3%81%AA%E6%8B%A1%E5%BC%B5%E3%82%B9%E3%82%AD%E3%83%BC%E3%83%9E)

**Comment by polyester-CTRL** [comment]
Goの署名用ライブラリがメンテナンスされているかは見ていませんでした……

well-knownな拡張スキーマについても書いておきました。

**Comment by cotton-alta** [comment]
LGTMです:tada: ご対応ありがとうございました！

こちらのissueはcloseしちゃいますね
