### ISSUE TITLE
設定画面の項目決め

### ISSUE THREAD

**Issue by para7** [stlatica/stlatica#349]
# Overview

設定画面にどんな項目を入れるのか検討する

# Completion Condition

# Reviewer

@para7
@cotton-alta 

# Sub Task

- [ ] Sub Task1
- [ ] Sub Task2

**Comment by cotton-alta** [comment]
https://scrapbox.io/stlatica/%E8%A8%AD%E5%AE%9A%E7%94%BB%E9%9D%A2%E3%81%AE%E9%A0%85%E7%9B%AE%E3%83%BB%E6%A7%8B%E9%80%A0
