### ISSUE TITLE
plat cellの不足要素追加

### ISSUE THREAD

**Issue by para7** [stlatica/stlatica#355]
# Overview

- 時刻表示がない
- plat 削除とか用のメニューを呼び出すボタンがない
- アイコン画像を src に埋め込んで表示する機能がない→埋め込むためのコンポーネントは既にある

~~画像に関しては　「画像IDを受け取って、Mapから画像データを引き出す」　という処理になるはず（本当は画像パスをそのまま渡したいけど base64 なので）~~

# Completion Condition

# Reviewer

# Sub Task

- [ ] Sub Task1
- [ ] Sub Task2

**Comment by nobuchi** [comment]
@para7 

時刻の表示ではTwitterのように"n時間前", "n分前"といった表示を実装しますか？
それとも最初のリリースでは投稿時刻を表示する方針ですか？

**Comment by para7** [comment]
@nobuchi 
日付表示コンポーネントとして分離しておけば後で容易に表示変更できると思うんで、一旦は実装が楽な時刻そのまま表示方式でいいと思います

後から追加しましょう
