### ISSUE TITLE
github運用ルールの作成

### ISSUE THREAD

**Issue by cotton-alta** [stlatica/stlatica#37]
# Overview

# Completion Condition

# Reviewer

# Sub Task

- [ ] Sub Task1
- [ ] Sub Task2

**Comment by cotton-alta** [comment]
@para7 

ざっくりとですがgithubの運用ルールについてまとめてみました
違和感だったり、不足点がないかご確認いただいてよろしいでしょうか:pray:

コメントがある場合、乱雑になるのを防ぐために引用してこちらのissue上に記載していただきたいです

https://scrapbox.io/stlatica/GitHub%E9%81%8B%E7%94%A8%E3%83%AB%E3%83%BC%E3%83%AB

**Comment by para7** [comment]
@cotton-alta 

誰が何の作業をしているのかgit上でもすぐ視認できるようにしておくと便利なのかなとも思ったのですがどうでしょう。

- ブランチ名にissue番号を含めておく
- 作業開始でgit pushしておく

など

とはいえissueやpull requestで紐付きますし、作業途中でもgitのツリー上での視認性を確保する利点は小さく面倒なだけな可能性もあるので、ルールとして決めておくべきかは判断頂きたいです。

----

その他

> TODOコメントを記載する場合、以下のようにsummaryとissueのリンクを貼ってください

既にいくつかTODOあるのでそのうち修正しておきます！

**Comment by cotton-alta** [comment]
>ブランチ名にissue番号を含めておく

こちらは適用した方が良さそうですね！:ok_man:
後からbranchの整理もしやすくなりそう

`<branch name>/#<issue number>`というようなformatにしようかと思います
e.g.) `setup_api/#50`

>作業開始でgit pushしておく

こちらはやらないで良さそうかな、とは思います。理由は以下のような感じです
- pushされていることで進捗の確認ができる -> privateでの開発ということもあり、そこまで厳密に管理しない
- pushされていることで重複作業に気づける -> 基本的にissueに対してのfeature branchを切ってもらうので、issueへのassignを明確にしておけば大丈夫そう

>既にいくつかTODOあるのでそのうち修正しておきます！

急ぎではないのでお手隙の際お願いします！:pray:

**Comment by cotton-alta** [comment]
@para7 

追記したのでお手隙の際、確認お願いします！
（真夜中にメンションすみません、、明日対応で全然大丈夫です）

**Comment by para7** [comment]
> <branch name>/#<issue number>というようなformatにしようかと思います

個人的には number / name で逆の方がしっくりは来るのですがフォーマット自体は異論ありません。
とはいえgithub でのタイトル表示が name #number になってるのでそちらの案の方がよさそうですね！

> こちらはやらないで良さそうかな、とは思います。

ですね、提案しといてあれですが微妙だなーとは思っていましたので却下で🆗です！

---

その他作成頂いているルールに疑問点はありません、こんな感じでよいと思います！👍

**Comment by cotton-alta** [comment]
ありがとうございます！
初版としてはこれで良さそうなのでこちらのissueはcloseしてしまいますね

不足点は今後出てくると思うのでその都度、更新していきましょう！ 🚀
