### ISSUE TITLE
github pages 404

### ISSUE THREAD

**Issue by para7** [stlatica/stlatica#393]
# Overview

https://github.com/stlatica/stlatica/actions/runs/8359717226

↓

https://stlatica.github.io/stlatica/

↓

404

# Completion Condition

開発中参照することはないと思われるので、今は放置でも特に問題なし

# Reviewer

# Sub Task

- [ ] Sub Task1
- [ ] Sub Task2

**Comment by Percy08-dev** [comment]
'./packages/frontend/ladle-build'の内容をデプロイする設定にしていましたが、フォルダがなくなってますね...

**Comment by para7** [comment]
@Percy08-dev 

ビルド成果物なのでgit上にはなく、アクション中で生成してデプロイするものですが、その生成がうまくいっていないということでしょうか？

>       #  コンポーネントカタログをビルド (2回目)
>      - name: catalog build
>        run: pnpm ci:ladle

今手元で pnpm ci:ladle を実行し frontend/ladle-build が生成されることは確認できたのですが……。

**Comment by para7** [comment]
なんかで 404 が出るからコメントアウトしたっぽいです。

https://github.com/stlatica/stlatica/blob/main/packages/frontend/.ladle/config.mjs

これっぽい
