### ISSUE TITLE
開発環境のDocker化

### ISSUE THREAD

**Issue by para7** [stlatica/stlatica#40]
# Overview

~~全てDocker化して構築手順書を無くしましょう！~~

~~特にバックエンド・フロントエンドで自分の担当しない領域は構築するだけで一苦労ですので、自動化しておきたいです。~~

【9/19】
Dockerコンテナ内特有の問題が色々出てくるっぽいので開発には向かないかもしれません #111 

とはいえ動作確認時や フロントエンド⇔バックエンド の接続時などクリーンな環境で動かせると嬉しい状況は確実にあるので、リリースまで見据えても本番向けビルドは用意しておく価値が十分にあります。

開発環境もあるに越したことはないですが、windows環境においてマウント時の動作速度が致命的に遅いことが発覚したため対応は後回しでよさそうです。（wslなら問題ないのですが…。）

（元々のモチベーションとしては　技術力バラバラなメンバーでも Docker に押し込むことで環境差異をなくしたかったのですが、Windowsの場合 WSLを組んでしっかり管理できる技術力がないと開発がまともに出来ないことが分かり前提がひっくり返った状態です。）

# Completion Condition

~~docker compose up -d~~
~~で開発スタートできるようにする~~

# Reviewer

# Sub Task

- [x] frontend
- [ ] backend

**Comment by para7** [comment]
フロントエンド構築はDocker化終わりました。
#27 #45

バックエンド部分は @cotton-alta 氏お願いいたします！🙏

**Comment by cotton-alta** [comment]
@polyester-CTRL 

遅くなりました:bow:
定例で話したバックエンドのdocker化についてやってもらいたいことをこちらに記載します:raising_hand_man:

- docker化するのは味気ないので、[air](https://github.com/cosmtrek/air)というツールを用いてホットリロードが効く構成にしてください
- 最終的にはMakefileにdockerでの起動用ターゲットを追加してそこから起動できるようにしてください（`make start-internalapi-docker`みたいなイメージ）
- Dockerfileが必要になりそうであれば別途dockerディレクトリなどを作ってそこに配置してください（airの設定ファイルもそこにおいてしまって大丈夫そう）

**Comment by para7** [comment]
#111 により前提が破綻し優先度が落ちたので記述を修正

**Comment by polyester-CTRL** [comment]
バックエンドについても、DockerをWindowsで使うときはWSLを使うという前提で進めます。
