### ISSUE TITLE
image削除のendpoint実装

### ISSUE THREAD

**Issue by cotton-alta** [stlatica/stlatica#408]
# Overview

# Completion Condition

# Reviewer

# Sub Task

- [ ] Sub Task1
- [ ] Sub Task2

**Comment by polyester-CTRL** [comment]
OpenAPIのyamlを準備中

**Comment by polyester-CTRL** [comment]
@cotton-alta 
OpenAPIによるコード生成を行いました。
ご確認お願いします。
