### ISSUE TITLE
ワイヤーフレームの作成

### ISSUE THREAD

**Issue by para7** [stlatica/stlatica#72]
# Overview

# Completion Condition

# Reviewer

# Sub Task

- [ ] Sub Task1
- [ ] Sub Task2

**Comment by nobuchi** [comment]
ぱらなさんの画面遷移図かをfigmaで描きました。
ダークモードの配色やsetting, profile画面の要素がわかりませんでした...
確認をお願いいたします。

https://www.figma.com/file/sN6uRJfcdPqIg30yYq8y0Z/Stlatica_%E3%83%AF%E3%82%A4%E3%83%A4%E3%83%BC%E3%83%95%E3%83%AC%E3%83%BC%E3%83%A0?type=design&node-id=0%3A1&mode=design&t=YhTLGF5lm60qFQ7t-1

**Comment by para7** [comment]
@nobuchi 
配色は私もセンスないので一旦画面配置の方だけコメントしておきます

左側の方だけメニューにしてるんだと思いますが、別の画面として実装して全画面使うか、モーダルウインドウに押し込むのがいいと思います
今回だと、設定画面は別画面実装、プロフィール設定はモーダルがよさそうですがどうでしょうか。

もし設定画面が複数あって選択させたい、という想定なら設定ボタンを押したら小さいメニューがポップアップする、ドロップダウンメニュー的な実装が良さそうです

いずれにせよ、左側のplat書き込みエリアはアプリのコア機能なので上書きしたくないですね。

という方針で修正お願いいたします！🙏

**Comment by para7** [comment]
あ。Languageの項目ありましたが英語化とか対応するなら全体に大きな影響が出ますしライブラリ等技術選定も関わってくるので、早めに決めないと大変になりそうです。
とりあえず私の方で次回定例の議題に記載しておきます。

**Comment by cotton-alta** [comment]
ワイヤーフレーム作成までは自分もレビュワーとして参加させてください:pray:

**Comment by nobuchi** [comment]
@para7 
@cotton-alta 

[idea-nobuchi-flow](https://www.figma.com/file/sN6uRJfcdPqIg30yYq8y0Z/Stlatica_%E3%83%AF%E3%82%A4%E3%83%A4%E3%83%BC%E3%83%95%E3%83%AC%E3%83%BC%E3%83%A0?type=design&node-id=72%3A343&mode=design&t=fHjoAl7UHsbhcAsk-1)

[（WIP）ワイヤーフレームで組み込んで欲しい機能](https://scrapbox.io/stlatica/%EF%BC%88WIP%EF%BC%89%E3%83%AF%E3%82%A4%E3%83%A4%E3%83%BC%E3%83%95%E3%83%AC%E3%83%BC%E3%83%A0%E3%81%A7%E7%B5%84%E3%81%BF%E8%BE%BC%E3%82%93%E3%81%A7%E6%AC%B2%E3%81%97%E3%81%84%E6%A9%9F%E8%83%BD)の項目をもとにワイヤーフレームの概形を作成しましたので確認をお願いいたします。

**Comment by para7** [comment]
@nobuchi 
全体的な雰囲気はこんな感じでよさそうです。
あと細かい調整になってくるので、これでOKとして試作に取り掛かり始めても良いかもしれませんね。

以下気になった箇所

- プロフィール設定画面のアイコン登録が、モーダルからモーダル開く感じになっていると思うんですが、色々と面倒なので可能なら工夫して1枚に収めたいですね。とはいえ良い案浮かばないのでこちらでも検討してみます
- 個人TL・フォロー数・フォロワー数などは、上部にタブを設けるなりすることで閉じずに切り替え出来たほうが使いやすい気がします

**Comment by cotton-alta** [comment]
@para7 

>あと細かい調整になってくるので、これでOKとして試作に取り掛かり始めても良いかもしれませんね。

あ、以前のmtgでコンペ的な感じにするという話が上がっていた気がするのですが、どう進めますか？

**Comment by para7** [comment]
@cotton-alta 

> あ、以前のmtgでコンペ的な感じにするという話が上がっていた気がするのですが、どう進めますか？

以前までの状況を見て 積極的に引っ張った方が良さそうかな？という判断があってコンペ的に進めるのはどうかなと提案したんですが、今回上げて頂いた内容でかなり解像度上がっていたのでこのままでよいかなと思ってます。
私のイメージともかなり近かったので、私が作っても似通ったものが出てくるだけで意味が薄くなりそうです。

あとなにより、先週 PS5 を購入して最近全く進捗が出ていないので！！

**Comment by para7** [comment]
@nobuchi 
本日定例で話したんですが、デザイン統一の問題とかが出てきたのでちょっと今後の進め方検討します。
またfigmaにコメントかけると教わったので今後何かあればそうします

**Comment by nobuchi** [comment]
頂いたご指摘をもとに修正を行いましたので確認をお願いします

[idea-nobuchi-flow-latest](https://www.figma.com/file/sN6uRJfcdPqIg30yYq8y0Z/Stlatica_%E3%83%AF%E3%82%A4%E3%83%A4%E3%83%BC%E3%83%95%E3%83%AC%E3%83%BC%E3%83%A0?type=design&node-id=102-2&mode=design)

**Comment by cotton-alta** [comment]
@nobuchi 

一旦、自分の方から気になったところは解決したのでこのまま進めてもらって大丈夫そうです！:ok_man:
進め方については上で話しているようにぱらなさんと相談してください！
